<a href="https://colab.research.google.com/github/bhavya5463/DA-LAB/blob/da-lab/MOVIES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd
from dateutil.parser import parse
df=pd.read_csv('/content/movies_1_.csv')
df

,Title,US Gross,Worldwide Gross,US DVD Sales,Production Budget,Release Date,MPAA Rating,Running Time (min),Distributor,Source,Major Genre,Creative Type,Director,Rotten Tomatoes Rating,IMDB Rating,IMDB Votes
0,The Land Girls,146083,146083,NaN,8000000.0,12-Jun-98,R,NaN,Gramercy,NaN,NaN,NaN,NaN,NaN,6.1,1071.0
1,"First Love, Last Rites",10876,10876,NaN,300000.0,7-Aug-98,R,NaN,Strand,NaN,Drama,NaN,NaN,NaN,6.9,207.0
2,I Married a Strange Person,203134,203134,NaN,250000.0,28-Aug-98,NaN,NaN,Lionsgate,NaN,Comedy,NaN,NaN,NaN,6.8,865.0
3,Let's Talk About Sex,373615,373615,NaN,300000.0,11-Sep-98,NaN,NaN,Fine Line,NaN,Comedy,NaN,NaN,13.0,NaN,NaN
4,Slam,1009819,1087521,NaN,1000000.0,9-Oct-98,R,NaN,Trimark,Original Screenplay,Drama,Contemporary Fiction,NaN,62.0,3.4,165.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3196,Zack and Miri Make a Porno,31452765,36851125,21240321.0,24000000.0,31-Oct-08,R,101.0,Weinstein Co.,Original Screenplay,Comedy,Contemporary Fiction,Kevin Smith,65.0,7.0,55687.0
3197,Zodiac,33080084,83080084,20983030.0,85000000.0,2-Mar-07,R,157.0,Paramount Pictures,Based on Book/Short Story,Thriller/Suspense,Dramatization,David Fincher,89.0,NaN,NaN
3198,Zoom,11989328,12506188,6679409.0,35000000.0,11-Aug-06,PG,NaN,Sony Pictures,Based on Comic/Graphic Novel,Adventure,Super Hero,Peter Hewitt,3.0,3.4,7424.0
3199,The Legend of Zorro,45575336,141475336,NaN,80000000.0,28-Oct-05,PG,129.0,Sony Pictures,Remake,Adventure,Historical Fiction,Martin Campbell,26.0,5.7,21161.0
3200,The Mask of Zorro,93828745,233700000,NaN,65000000.0,17-Jul-98,PG-13,136.0,Sony Pictures,Remake,Adventure,Historical Fiction,Martin Campbell,82.0,6.7,4789.0

In [17]:
#pre-processing
import pandas as pd
from dateutil.parser import parse
df1=df.copy()
for i in range(len(df['Release Date'])):
  if(df['Release Date'][i]=='TBD'):
    df1=df1.drop(i)
  else:
    df1['Release Date'][i]=parse(df['Release Date'][i]).date()
df1.index=range(len(df1))
df1['Release Date']=pd.to_datetime(df1['Release Date'])
df1['year']=df1['Release Date'].dt.year
df1['month']=df1['Release Date'].dt.month
df1['day']=df1['Release Date'].dt.day
df1

<ipython-input-17-d2e6f0bc7e6a>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Release Date'][i]=parse(df['Release Date'][i]).date()

,Title,US Gross,Worldwide Gross,US DVD Sales,Production Budget,Release Date,MPAA Rating,Running Time (min),Distributor,Source,Major Genre,Creative Type,Director,Rotten Tomatoes Rating,IMDB Rating,IMDB Votes,year,month,day
0,The Land Girls,146083,146083,NaN,8000000.0,1998-06-12,R,NaN,Gramercy,NaN,NaN,NaN,NaN,NaN,6.1,1071.0,1998,6,12
1,"First Love, Last Rites",10876,10876,NaN,300000.0,1998-08-07,R,NaN,Strand,NaN,Drama,NaN,NaN,NaN,6.9,207.0,1998,8,7
2,I Married a Strange Person,203134,203134,NaN,250000.0,1998-08-28,NaN,NaN,Lionsgate,NaN,Comedy,NaN,NaN,NaN,6.8,865.0,1998,8,28
3,Let's Talk About Sex,373615,373615,NaN,300000.0,1998-09-11,NaN,NaN,Fine Line,NaN,Comedy,NaN,NaN,13.0,NaN,NaN,1998,9,11
4,Slam,1009819,1087521,NaN,1000000.0,1998-10-09,R,NaN,Trimark,Original Screenplay,Drama,Contemporary Fiction,NaN,62.0,3.4,165.0,1998,10,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3189,Zack and Miri Make a Porno,31452765,36851125,21240321.0,24000000.0,2008-10-31,R,101.0,Weinstein Co.,Original Screenplay,Comedy,Contemporary Fiction,Kevin Smith,65.0,7.0,55687.0,2008,10,31
3190,Zodiac,33080084,83080084,20983030.0,85000000.0,2007-03-02,R,157.0,Paramount Pictures,Based on Book/Short Story,Thriller/Suspense,Dramatization,David Fincher,89.0,NaN,NaN,2007,3,2
3191,Zoom,11989328,12506188,6679409.0,35000000.0,2006-08-11,PG,NaN,Sony Pictures,Based on Comic/Graphic Novel,Adventure,Super Hero,Peter Hewitt,3.0,3.4,7424.0,2006,8,11
3192,The Legend of Zorro,45575336,141475336,NaN,80000000.0,2005-10-28,PG,129.0,Sony Pictures,Remake,Adventure,Historical Fiction,Martin Campbell,26.0,5.7,21161.0,2005,10,28
3193,The Mask of Zorro,93828745,233700000,NaN,65000000.0,1998-07-17,PG-13,136.0,Sony Pictures,Remake,Adventure,Historical Fiction,Martin Campbell,82.0,6.7,4789.0,1998,7,17

In [31]:
#1.	 (i). Find out the no of movies released in every month of the year 1995.
g=df1[df1['year']==1995]
k=g.groupby('month')['Title'].count()
k

month
1      3
2      2
3      3
4      5
5      6
6      7
7      8
8      7
9      4
10     8
11     7
12    13
Name: Title, dtype: int64

In [34]:
#(ii). Find out the no. of movies released in every year from 1990 to 1998
k=df1[(df1['year']>=1990) & (df1['year']<=1998)]
g=k.groupby('year')['Title'].count()
g

year
1990     28
1991     33
1992     28
1993     39
1994     52
1995     73
1996     99
1997     97
1998    144
Name: Title, dtype: int64

In [37]:
#2.	(i). Find no. of movies released under each genre given in the database.
k=df1.groupby('Major Genre')['Title'].count()
k

Major Genre
Action                 420
Adventure              274
Black Comedy            36
Comedy                 675
Concert/Performance      5
Documentary             43
Drama                  789
Horror                 219
Musical                 53
Romantic Comedy        137
Thriller/Suspense      239
Western                 36
Name: Title, dtype: int64

In [45]:
#(ii). Find the movies under each genre with 1MDB rating >7 and rotten tomatoes rating > 60.
k=df1[(df1['IMDB Rating']>7) & (df1['Rotten Tomatoes Rating']>60)]
g=k.groupby(['Major Genre','Title'])['Title'].count()
g

Major Genre  Title
Action       A Bridge Too Far                                              1
             Aliens                                                        1
             Apocalypse Now                                                1
             Avatar                                                        1
             Batman                                                        1
                                                                          ..
Western      Pale Rider                                                    1
             The Assassination of Jesse James by the Coward Robert Ford    1
             The Ballad of Cable Hogue                                     1
             The Wild Bunch                                                1
             Tombstone                                                     1
Name: Title, Length: 541, dtype: int64

In [54]:
#3.	(i). Find the movies released under each fiction with each director in the ascending order of release dates.
k=df1.sort_values(by='Release Date',ascending=True)
g=k.groupby(['Creative Type','Director','Title'])['Title'].count()
g

Creative Type         Director       Title
Contemporary Fiction  Adam McKay     Talladega Nights: The Ballad of Ricky Bobby    1
                      Adam Shankman  A Walk to Remember                             1
                                     Bringing Down the House                        1
                                     Cheaper by the Dozen 2                         1
                                     The Pacifier                                   1
                                                                                   ..
Super Hero            Tim Burton     Batman Returns                                 1
                      Tim Story      Fantastic Four                                 1
                                     Fantastic Four: Rise of the Silver Surfer      1
                      Warren Beatty  Dick Tracy                                     1
                      Zack Snyder    Watchmen                                       1
Name: Title, Length: 1695, dtype: int64

In [57]:
#(ii). Find movies released under each distributor in the order of genre and director
k=df1.sort_values(by=['Major Genre','Director'],ascending=True)
g=k.groupby(['Distributor','Title'])['Title'].count()
g

Distributor       Title
20th Century Fox  12 Rounds                   1
                  28 Weeks Later              1
                  A Good Year                 1
                  AVP: Alien Vs. Predator     1
                  Alexander's Ragtime Band    1
                                             ..
Yash Raj Films    Veer-Zaara                  1
Zeitgeist         AimÈe & Jaguar              1
                  Following                   1
                  Nowhere in Africa           1
                  Travellers and Magicians    1
Name: Title, Length: 2962, dtype: int64

In [66]:
#4.	(i). Find the movies released world-wide and find out the revenue received world-wide other than US with their ratings.
df1['Worldwide Gross']=pd.to_numeric(df1['Worldwide Gross'],errors='coerce')
df1['US Gross']=pd.to_numeric(df1['US Gross'],errors='coerce')
df1['revenue']=df1['Worldwide Gross']-df1['US Gross']
df1[['Title','IMDB Rating','revenue']]

                           Title  IMDB Rating      revenue
0                 The Land Girls          6.1          0.0
1         First Love, Last Rites          6.9          0.0
2     I Married a Strange Person          6.8          0.0
3           Let's Talk About Sex          NaN          0.0
4                           Slam          3.4      77702.0
...                          ...          ...          ...
3189  Zack and Miri Make a Porno          7.0    5398360.0
3190                      Zodiac          NaN   50000000.0
3191                        Zoom          3.4     516860.0
3192         The Legend of Zorro          5.7   95900000.0
3193           The Mask of Zorro          6.7  139871255.0

[3194 rows x 3 columns]

In [73]:
#(ii). Find the movies with loss & profit released in each year with genre and ratings.
df1['Production Budget']=pd.to_numeric(df1['Production Budget'],errors='coerce')
df1['p and l']=df1['Production Budget']-df1['Worldwide Gross']
p=df1.groupby('year')
for i,j in p:
  print("year : ",i)
  print(j[["Title","Major Genre","IMDB Rating","p and l"]])
  print("\n")

year :  1929
                   Title Major Genre  IMDB Rating    p and l
114  The Broadway Melody     Musical          6.7 -3979000.0


year :  1930
             Title Major Genre  IMDB Rating  p and l
403  Hell's Angels         NaN          7.9      NaN


year :  1931
         Title Major Genre  IMDB Rating   p and l
570  Mata Hari         NaN          2.2 -342000.0


year :  1934
                     Title      Major Genre  IMDB Rating    p and l
948  It Happened One Night  Romantic Comedy          8.3 -2175000.0


year :  1938
                           Title Major Genre  IMDB Rating    p and l
51      Alexander's Ragtime Band       Drama          NaN -2000000.0
1047  You Can't Take It With You         NaN          8.0 -2356000.0


year :  1939
                            Title Major Genre  IMDB Rating    p and l
621  Mr. Smith Goes To Washington       Drama          8.2 -7500000.0


year :  1940
         Title Major Genre  IMDB Rating    p and l
115  Boom Town         NaN          7.1 -7172000.0
752    Rebecca       Drama          8.4 -4712000.0


year :  1942
          Title Major Genre  IMDB Rating    p and l
213  Casablanca       Drama          8.8 -9512500.0


year :  1944
              Title Major Genre  IMDB Rating    p and l
141  Bathing Beauty     Musical          6.2 -1139000.0


year :  1945
                       Title Major Genre  IMDB Rating    p and l
547         The Lost Weekend         NaN          8.2 -9750000.0
881               Spellbound         NaN          7.7 -5500000.0
1001  The Valley of Decision         NaN          7.3 -6972000.0


year :  1946
                     Title Major Genre  IMDB Rating     p and l
452  It's a Wonderful Life         NaN          8.7  -3420000.0
659              Notorious         NaN          6.3 -22464742.0


year :  1947
                     Title Major Genre  IMDB Rating    p and l
382  Gentleman's Agreement         NaN          7.4 -5800000.0


year :  1948
          Title Major Genre  IMDB Rating    p and l
708  The Pirate         NaN          7.1   744000.0
766   Red River         NaN          7.8 -6012000.0


year :  1949
                        Title Major Genre  IMDB Rating    p and l
917         Sands of Iwo Jima         NaN          7.1 -6800000.0
923  She Wore a Yellow Ribbon         NaN          7.3 -3800000.0


year :  1952
         Title Major Genre  IMDB Rating    p and l
412  High Noon         NaN          8.3 -7270000.0


year :  1954
            Title Major Genre  IMDB Rating     p and l
284  The Egyptian         NaN          6.2 -10000000.0


year :  1956
               Title Major Genre  IMDB Rating     p and l
540   Love Me Tender         NaN          5.9  -8000000.0
580        Moby Dick   Adventure          7.4  -5900000.0
974          Trapeze         NaN          6.7 -10400000.0
1031   War and Peace         NaN          6.8  -6500000.0


year :  1957
                  Title Major Genre  IMDB Rating    p and l
300  A Farewell To Arms         NaN          6.6 -6000000.0


year :  1959
               Title Major Genre  IMDB Rating    p and l
651  The Nun's Story         NaN          7.5 -9300000.0


year :  1960
             Title      Major Genre  IMDB Rating     p and l
60   The Apartment  Romantic Comedy          8.4 -21600000.0
529   Elmer Gantry              NaN          7.8  -7400000.0


year :  1961
                     Title Major Genre  IMDB Rating    p and l
624            The Misfits         NaN          7.4 -4200000.0
696  Pocketful of Miracles         NaN          7.2 -2100000.0


year :  1963
                 Title Major Genre  IMDB Rating    p and l
38   55 Days at Peking       Drama          6.8  7000000.0
258     Donovan's Reef         NaN          6.6 -3914000.0


year :  1965
                  Title Major Genre  IMDB Rating      p and l
873  The Sound of Music     Musical          6.3 -278014286.0


year :  1967
             Title Major Genre  IMDB Rating    p and l
461  In Cold Blood         NaN          8.1 -9500000.0


year :  1968
       Title Major Genre  IMDB Rating    p and l
831  Shalako         NaN          5.3 -1165000.0


year :  1969
             Title Major Genre  IMDB Rating     p and l
916  Sweet Charity         NaN          7.0  12000000.0


year :  1970
                  Title Major Genre  IMDB Rating    p and l
597  The Molly Maguires         NaN          6.8  8800000.0


year :  1971
                                  Title Major Genre  IMDB Rating    p and l
291  Escape from the Planet of the Apes         NaN          6.1 -9800000.0


year :  1972
                                  Title Major Genre  IMDB Rating    p and l
201  Conquest of the Planet of the Apes         NaN          5.8 -8000000.0


year :  1973
                                  Title Major Genre  IMDB Rating      p and l
54                    American Graffiti      Comedy          7.6 -139223000.0
93    Battle for the Planet of the Apes         NaN          5.0   -7000000.0
507                    Live and Let Die      Action          6.8 -154800000.0
699       Pat Garrett and Billy the Kid         NaN          7.3   -6361217.0
851                             Sleeper      Comedy          7.3  -16344729.0
902                           The Sting         NaN          8.4 -154116327.0
1045                       The Exorcist      Horror          8.1 -390500000.0


year :  1974
                            Title        Major Genre  IMDB Rating      p and l
87                          Benji          Adventure          5.8  -31059560.0
139               Blazing Saddles             Comedy          7.8 -116900000.0
224              The Conversation  Thriller/Suspense          8.1   -2820000.0
342                The Front Page             Comedy          7.2  -11000000.0
365        The Godfather: Part II                NaN          9.0  -44300000.0
632   The Man with the Golden Gun             Action          6.7  -90600000.0
930   The Texas Chainsaw Massacre             Horror          6.1  -26432439.0
986              Towering Inferno                NaN          NaN -125700000.0
1050           Young Frankenstein                NaN          8.0  -83500000.0


year :  1975
                               Title Major Genre  IMDB Rating      p and l
69                      Barry Lyndon       Drama          8.1   -9000000.0
266                  Death Race 2000         NaN          6.1          NaN
486                             Jaws      Horror          8.3 -458700000.0
535                   Love and Death      Comedy          7.6  -17123742.0
605  Monty Python and the Holy Grail         NaN          8.4   -4628948.0
673  One Flew Over the Cuckoo's Nest         NaN          8.9 -104581275.0
775    The Rocky Horror Picture Show     Musical          7.1 -138676417.0


year :  1976
                Title Major Genre  IMDB Rating      p and l
107     The Blue Bird         NaN          4.9     313000.0
158            Carrie      Horror          7.4  -24078153.0
302       Family Plot         NaN          6.8  -10200000.0
495         King Kong         NaN          7.6  -67614445.0
549       Logan's Run         NaN          6.7  -18000000.0
676          The Omen      Horror          5.4  -45770885.0
749  Robin and Marian         NaN          6.5   -3000000.0
779             Rocky         NaN          4.0 -224000000.0
867      Silent Movie      Comedy          6.4  -31745695.0
987       Taxi Driver       Drama          8.6  -20100000.0


year :  1977
                                   Title Major Genre  IMDB Rating      p and l
57                            Annie Hall      Comedy          8.2  -34251425.0
143                     A Bridge Too Far      Action          7.3  -24800000.0
163   Close Encounters of the Third Kind   Adventure          7.8 -317700000.0
254                      Damnation Alley         NaN          4.7          NaN
293                           Eraserhead         NaN          7.4   -6900000.0
297             Exorcist II: The Heretic      Horror          3.5  -11011000.0
450                         High Anxiety         NaN          6.5  -27663038.0
499               Kingdom of the Spiders         NaN          5.7  -16500000.0
609                         March or Die         NaN          6.1    6000000.0
668                   New York, New York     Musical          6.7     200000.0
698                        Pete's Dragon         NaN          6.0  -26000000.0
889                         The Sorcerer         NaN          6.8    9600000.0
909         Star Wars Ep. IV: A New Hope   Adventure          NaN -786900000.0
918                 The Spy Who Loved Me      Action          7.1 -171400000.0
2107            The Kentucky Fried Movie      Comedy          6.4  -19400000.0


year :  1978
                                Title        Major Genre  IMDB Rating  \
153              The Boys from Brazil  Thriller/Suspense          7.0
198                       Coming Home                NaN          7.3
210                          Caravans          Adventure          5.8
299            Force 10 from Navarone             Action          6.0
326                           F.I.S.T              Drama          6.2
420                         Halloween             Horror          6.0
487                            Jaws 2             Horror          5.6
648   National Lampoon's Animal House                NaN          NaN
887                          Superman          Adventure          4.9
1018                          The Wiz            Musical          4.5
1859                           Grease            Musical          7.0

          p and l
153    -7000000.0
198   -29653000.0
210    13000000.0
299    -2100000.0
326    -9388920.0
420   -69675000.0
487  -188900376.0
648  -138600000.0
887  -245200000.0
1018   11000000.0
1859 -200005260.0


year :  1979
                              Title  Major Genre  IMDB Rating      p and l
22                             1941       Comedy          5.6  -62875000.0
61                   Apocalypse Now       Action          8.6  -47300000.0
99                   The Black Hole          NaN          5.6  -15841901.0
238                Dawn of the Dead       Horror          7.4  -53500000.0
265                         Dolphin  Documentary          5.8     156000.0
268                 The Deer Hunter        Drama          8.2  -35000000.0
395   The First Great Train Robbery       Action          6.9    5608058.0
613                       Moonraker       Action          6.1 -179300000.0
616               The Life of Brian       Comedy          NaN  -16008693.0
628                          Meteor          NaN          4.7    7600000.0
728                        Prophecy          NaN          4.7   -9000000.0
741           The Prisoner of Zenda       Comedy          4.6    5500000.0
893   Star Trek: The Motion Picture    Adventure          6.2 -104000000.0
1140                          Alien       Horror          8.5 -194630630.0


year :  1980
                                        Title Major Genre  IMDB Rating  \
111                        The Blues Brothers     Musical          7.9
155                                Caddyshack      Comedy          7.3
216                      Can't Stop the Music     Musical          3.5
271                           Dressed to Kill         NaN          7.1
286                          The Elephant Man         NaN          8.4
288  Star Wars Ep. V: The Empire Strikes Back   Adventure          NaN
307                           Friday the 13th      Horror          5.6
329                              Flash Gordon      Action          6.2
338                                   The Fog      Horror          3.3
423                               Home Movies         NaN          5.3
445                             Heaven's Gate         NaN          6.5
467                                The Island   Adventure          6.9
519                        Lion of the Desert         NaN          7.8
541                           The Long Riders      Action          7.1
572                                    Maniac         NaN          6.2
601                                   Mad Max      Action          6.9
680                           Ordinary People       Drama          7.0
717                              Penitentiary       Drama          5.5
722                                    Popeye         NaN          4.9
756                               Raging Bull       Drama          8.4
793                                 Airplane!      Comedy          7.8
796                         Raise the Titanic         NaN          3.9
834                               The Shining      Horror          8.5
863                         Somewhere in Time       Drama          7.0
936                              Terror Train         NaN          5.5

         p and l
111  -30229890.0
155  -33846344.0
216   18000000.0
271  -25399000.0
286  -21010864.0
288 -511171960.0
307  -59204601.0
329    7892040.0
338  -20378361.0
423     310866.0
445   40515669.0
467    6283172.0
519   33500000.0
541   -5198912.0
572   -9650000.0
601  -99550000.0
680  -46302978.0
717    -187000.0
722  -29823037.0
756   -5380203.0
793  -79953539.0
796   33000000.0
834  -25017374.0
863   -4609597.0
936   -4500000.0


year :  1981
                              Title        Major Genre  IMDB Rating  \
35                 The Four Seasons             Comedy          7.0
112                        Blow Out  Thriller/Suspense          7.1
170                Chariots of Fire              Drama          7.3
186             Clash of the Titans          Adventure          5.9
269                    Dragonslayer             Action          6.8
289            Escape from New York             Action          7.1
318          Friday the 13th Part 2             Horror          5.5
357              For Your Eyes Only             Action          6.8
361                       Gallipoli                NaN          7.7
364                  Graduation Day  Thriller/Suspense          3.0
402                     Heavy Metal          Adventure          6.0
404                      Heartbeeps             Comedy          4.1
413    History of the World: Part I             Comedy          6.5
415                    Halloween II             Horror          4.9
431                     The Howling                NaN          6.5
538   The Legend of the Lone Ranger            Western          4.6
587                 Modern Problems             Comedy          4.5
608                  Mommie Dearest              Drama          6.3
643                      Nighthawks             Action          6.3
718      The Pursuit of D.B. Cooper          Adventure          5.8
733  The Postman Always Rings Twice                NaN          6.4
765         Raiders of the Lost Ark          Adventure          8.7
767                            Reds              Drama          7.4
789                            Roar                NaN          5.9
879                          Sphinx  Thriller/Suspense          4.9
884                     Superman II          Adventure          6.7
907                         Stripes             Comedy          6.8
954                    Time Bandits          Adventure          6.9
962                            Taps              Drama          6.5
996               Under the Rainbow             Comedy          4.9

         p and l
35   -35988161.0
112    4252766.0
170  -51659946.0
186  -15000000.0
269   12000000.0
289  -19244700.0
318  -20472776.0
357 -167300000.0
361   -2732587.0
364  -23644000.0
402  -10271091.0
404    4000000.0
413  -20672000.0
415  -23033818.0
431  -16985000.0
538    4600000.0
587  -16474312.0
608  -20032000.0
643  -14600000.0
718    9895836.0
733  -32200000.0
765 -366800358.0
767  -16500000.0
789   15000000.0
879   -1400000.0
884  -58185706.0
907  -75300000.0
954  -25400000.0
962  -21856053.0
996    1173510.0


year :  1982
                                  Title        Major Genre  IMDB Rating  \
84                      The Beastmaster             Action          5.7
109                        Blade Runner  Thriller/Suspense          8.3
192                 Conan the Barbarian             Action          6.8
194                       Class of 1984              Drama          6.3
206                           Creepshow             Horror          6.5
228                           Boot, Das              Drama          4.3
250                               Diner             Comedy          7.1
295           ET: The Extra-Terrestrial              Drama          7.9
308              Friday the 13th Part 3             Horror          5.5
343                         First Blood             Action          7.4
346                             Firefox             Action          5.6
353        Fast Times at Ridgemont High             Comedy          7.2
380                              Gandhi              Drama          8.2
416    Halloween 3: Season of the Witch             Horror          3.8
480   Jekyll and Hyde... Together Again             Comedy          5.5
592                           Megaforce             Action          2.5
599         Mad Max 2: The Road Warrior             Action          NaN
603            The Man From Snowy River              Drama          7.0
637                              Inchon              Drama          3.0
700                         Poltergeist             Horror          7.4
720                             Porky's             Comedy          5.8
743                                   Q             Horror          6.1
746                    La Guerre du feu          Adventure          7.4
900     Star Trek II: The Wrath of Khan          Adventure          7.8
973                                Tron             Action          2.9
981                             Tootsie             Comedy          7.4
1003                        The Verdict              Drama          7.7

          p and l
84     -5751126.0
109    -5139618.0
192   -18264085.0
194    -3715361.0
206   -12036244.0
228   -72970337.0
250    -7592907.0
295  -782410554.0
308   -34440067.0
343  -111212904.0
346   -24785720.0
353   -22592880.0
380   -30767889.0
416   -11900000.0
480     1292417.0
592    12324401.0
599   -22600832.0
603   -15659423.0
637    41591364.0
700  -111006019.0
720  -105492484.0
743      945000.0
746    -8459585.0
900   -84800000.0
973    -9918576.0
981  -162200000.0
1003  -37977250.0


year :  1983
                                     Title        Major Genre  IMDB Rating  \
91           The Ballad of Gregorio Cortez            Western          NaN
135                             Brainstorm  Thriller/Suspense          6.3
171                      A Christmas Story             Comedy          8.0
245                          The Dead Zone             Horror          7.3
278                          The Evil Dead             Horror          7.6
327                             Flashdance              Drama          5.6
542                              Losin' It                NaN          4.6
564                      Lone Wolf McQuade             Action          5.8
660                  Never Say Never Again             Action          6.0
671                              Octopussy             Action          6.6
687                          The Outsiders              Drama          7.0
770   Star Wars Ep. VI: Return of the Jedi          Adventure          NaN
774                        The Right Stuff             Action          7.9
813                               Scarface              Drama          8.2
885                           Superman III          Adventure          4.7
990               Twilight Zone: The Movie             Horror          6.3
998                             Videodrome             Horror          7.3
1029                             War Games  Thriller/Suspense          6.4
1051                                 Yentl            Musical          6.2

          p and l
91       396000.0
135     6078950.0